/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.UConnection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Omar
 */
public class PrincipalAdmi extends javax.swing.JFrame {
InicioAdmi iniadm = new InicioAdmi();
JTextField aux;
int id ;

    /**
     * Creates new form PrincipalAdmi
     */
    public PrincipalAdmi() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregaVideo = new javax.swing.JButton();
        btnActualizaAlbum = new javax.swing.JButton();
        btnEliminarMultimedia = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnVerInventario = new javax.swing.JButton();
        btnActualizaVideo = new javax.swing.JButton();
        btnActualizaCancion = new javax.swing.JButton();
        btnAgregaAlbum = new javax.swing.JButton();
        btnIngresaCancion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Inicio");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setText("Biemvenido");

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setText("Usuario:");

        jlbUsuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jlbIdUsuario.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jlbImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jlbIdUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(131, 131, 131)
                .addComponent(jlbImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlbIdUsuario)))
            .addComponent(jlbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        btnAgregaVideo.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregaVideo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregaVideo.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregaVideo.setText("Ingresar Video");
        btnAgregaVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaVideoActionPerformed(evt);
            }
        });

        btnActualizaAlbum.setBackground(new java.awt.Color(0, 0, 255));
        btnActualizaAlbum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizaAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizaAlbum.setText("Actualizar Álbum");
        btnActualizaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaAlbumActionPerformed(evt);
            }
        });

        btnEliminarMultimedia.setBackground(new java.awt.Color(0, 0, 255));
        btnEliminarMultimedia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminarMultimedia.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarMultimedia.setText("Eliminar Multimedia");
        btnEliminarMultimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMultimediaActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnVerInventario.setBackground(new java.awt.Color(0, 0, 255));
        btnVerInventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerInventario.setForeground(new java.awt.Color(255, 255, 255));
        btnVerInventario.setText("Inventario");
        btnVerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInventarioActionPerformed(evt);
            }
        });

        btnActualizaVideo.setBackground(new java.awt.Color(0, 0, 255));
        btnActualizaVideo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizaVideo.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizaVideo.setText("Actualizar Video");
        btnActualizaVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaVideoActionPerformed(evt);
            }
        });

        btnActualizaCancion.setBackground(new java.awt.Color(0, 0, 255));
        btnActualizaCancion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizaCancion.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizaCancion.setText("Actualizar Canción");
        btnActualizaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizaCancionActionPerformed(evt);
            }
        });

        btnAgregaAlbum.setBackground(new java.awt.Color(0, 0, 255));
        btnAgregaAlbum.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregaAlbum.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregaAlbum.setText("Ingresa Álbum");
        btnAgregaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaAlbumActionPerformed(evt);
            }
        });

        btnIngresaCancion.setBackground(new java.awt.Color(0, 0, 204));
        btnIngresaCancion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresaCancion.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresaCancion.setText("Ingresa Canción");
        btnIngresaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnIngresaCancion)
                            .addGap(52, 52, 52)
                            .addComponent(btnActualizaCancion))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregaVideo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizaVideo))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregaAlbum)
                                .addGap(24, 24, 24)
                                .addComponent(btnActualizaAlbum)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(btnEliminarMultimedia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnVerInventario))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizaCancion)
                    .addComponent(btnIngresaCancion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregaAlbum)
                    .addComponent(btnActualizaAlbum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregaVideo)
                    .addComponent(btnActualizaVideo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMultimedia)
                    .addComponent(btnVerInventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Elige una opción: ");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaAlbumActionPerformed
    ActualizarAlbum ActAlbum = new ActualizarAlbum();
    ActAlbum.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnActualizaAlbumActionPerformed

    private void btnActualizaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaVideoActionPerformed
    ActualizarVideo ActVideo = new ActualizarVideo();
    ActVideo.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnActualizaVideoActionPerformed

    private void btnActualizaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizaCancionActionPerformed
    ActualizarCancion Actcancion = new ActualizarCancion();
    Actcancion.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnActualizaCancionActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved

    }//GEN-LAST:event_jPanel1MouseMoved

    private void btnAgregaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaAlbumActionPerformed
    Album album = new Album();
    album.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnAgregaAlbumActionPerformed

    private void btnAgregaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaVideoActionPerformed
    Video video = new Video();
    video.setVisible(true);
    this.setVisible(false);      
    }//GEN-LAST:event_btnAgregaVideoActionPerformed

    private void btnEliminarMultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMultimediaActionPerformed
    EliminarMultimedia eliminar = new EliminarMultimedia();
    eliminar.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnEliminarMultimediaActionPerformed

    private void btnVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInventarioActionPerformed
    VistaInventario inventario = new VistaInventario();
    inventario.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnVerInventarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     int v = JOptionPane.showConfirmDialog(this,
             "¿Estas seguro de salir de esta ventan?\n"
             + "Si abandonas la ventana se perdera el proceso",
             "¡¡ADVERTENCIA!!", JOptionPane.YES_NO_OPTION);
        if (v == JOptionPane.YES_OPTION) {
            InicioPrincipal iniP = new InicioPrincipal();
            iniP.setVisible(true);
            this.setVisible(false);
        } else {
             JOptionPane.showMessageDialog(null,
                     "Sigue con la selección del menu.",
                     "¡¡CONTINUAR!!", JOptionPane.INFORMATION_MESSAGE);
          }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //id = Integer.parseInt(jlbIdUsuario.getText()); 
        try{
            PreparedStatement ps = null;
            ImageIcon foto;
            InputStream is;
            ResultSet rs = null;
            UConnection conn = new UConnection();
            Connection con = UConnection.getConnection();
            String sql = "SELECT nombreA, imgAdmi"
                    + " FROM administrador WHERE idAdmi=?";
            ps = con.prepareStatement(sql);
            ps.setInt(1, Integer.parseInt(jlbIdUsuario.getText()));
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnas = rsmd.getColumnCount();
            while (rs.next()) {
                jlbUsuario.setText(rs.getString(1));
                is = rs.getBinaryStream(2);
                BufferedImage bi = ImageIO.read(is);
                foto = new ImageIcon(bi);
                Image img = foto.getImage();
                Image newImg = img.getScaledInstance(140,
                        170, java.awt.Image.SCALE_SMOOTH);
                ImageIcon newIcon = new ImageIcon(newImg);
                jlbImg.setIcon(newIcon);
            }
        } catch (SQLException e) {
            System.out.println(e.toString());
        } catch (IOException ex) {
        Logger.getLogger(PrincipalAdmi.class.getName()).log(
                Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnIngresaCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaCancionActionPerformed
     Cancion cancion = new Cancion();
     cancion.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_btnIngresaCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalAdmi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizaAlbum;
    private javax.swing.JButton btnActualizaCancion;
    private javax.swing.JButton btnActualizaVideo;
    private javax.swing.JButton btnAgregaAlbum;
    private javax.swing.JButton btnAgregaVideo;
    private javax.swing.JButton btnEliminarMultimedia;
    private javax.swing.JButton btnIngresaCancion;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static final javax.swing.JLabel jlbIdUsuario = new javax.swing.JLabel();
    public static final javax.swing.JLabel jlbImg = new javax.swing.JLabel();
    public static final javax.swing.JLabel jlbUsuario = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
